const transactions = [
    {
        TransId:"1",
        AccId : 1,
        TransLib : "Lib transaction id:1 compte id:1",
        TransDate : "27/02/2024",
        TransType : {id:1,name:"Electronic"},
        TransCategory : {id:1,name:"Food"},
        TransAmount : "8.00",
        TransBalance : "298.00",
        TransNote : "Loren Ipsum",
    },
    {
        TransId:"2",
        AccId : 1,
        TransLib : "Lib transaction id:2 compte id:1",
        TransDate : "27/02/2024",
        TransType : {id:1,name:"Electronic"},
        TransCategory : {id:1,name:"Food"},
        TransAmount : "8.00",
        TransBalance : "298.00",
        TransNote : "Loren Ipsum",
    },
    {
        TransId:"3",
        AccId : 3,
        TransLib : "Lib transaction id:3 compte id:3",
        TransDate : "27/02/2024",
        TransType : {id:1,name:"Electronic"},
        TransCategory : {id:1,name:"Food"},
        TransAmount : "8.00",
        TransBalance : "298.00",
        TransNote : "Loren Ipsum",
    },
    {
        TransId:"4",
        AccId : 2,
        TransLib : "Lib transaction id:4 compte id:2",
        TransDate : "27/02/2024",
        TransType : {id:1,name:"Electronic"},
        TransCategory : {id:1,name:"Food"},
        TransAmount : "8.00",
        TransBalance : "298.00",
        TransNote : "Loren Ipsum",
    },
    {
        TransId:"5",
        AccId : 3,
        TransLib : "Lib transaction id:5 compte id:3",
        TransDate : "27/02/2024",
        TransType : {id:1,name:"Electronic"},
        TransCategory : {id:1,name:"Food"},
        TransAmount : "8.00",
        TransBalance : "298.00",
        TransNote : "Loren Ipsum",
    },
    {
        TransId:"6",
        AccId : 2,
        TransLib : "Lib transaction id:6 compte id:2",
        TransDate : "27/02/2024",
        TransType : {id:1,name:"Electronic"},
        TransCategory : {id:1,name:"Food"},
        TransAmount : "8.00",
        TransBalance : "298.00",
        TransNote : "Loren Ipsum",
    },
    {
        TransId:"7",
        AccId : 1,
        TransLib : "Lib transaction id:7 compte id:1",
        TransDate : "27/02/2024",
        TransType : {id:1,name:"Electronic"},
        TransCategory : {id:1,name:"Food"},
        TransAmount : "8.00",
        TransBalance : "298.00",
        TransNote : "Loren Ipsum",
    },
    {
        TransId:"8",
        AccId : 3,
        TransLib : "Lib transaction id:8 compte id:3",
        TransDate : "27/02/2024",
        TransType : {id:1,name:"Electronic"},
        TransCategory : {id:1,name:"Food"},
        TransAmount : "8.00",
        TransBalance : "298.00",
        TransNote : "Loren Ipsum",
    },
    {
        TransId:"9",
        AccId : 2,
        TransLib : "Lib transaction id:9 compte id:2",
        TransDate : "27/02/2024",
        TransType : {id:1,name:"Electronic"},
        TransCategory : {id:1,name:"Food"},
        TransAmount : "8.00",
        TransBalance : "298.00",
        TransNote : "Loren Ipsum",
    },
    {
        TransId:"10",
        AccId : 3,
        TransLib : "Lib transaction id:10 compte id:3",
        TransDate : "27/02/2024",
        TransType : {id:1,name:"Electronic"},
        TransCategory : {id:1,name:"Food"},
        TransAmount : "8.00",
        TransBalance : "298.00",
        TransNote : "Loren Ipsum",
    },
    {
        TransId:"11",
        AccId : 1,
        TransLib : "Lib transaction id:11 compte id:1",
        TransDate : "27/02/2024",
        TransType : {id:1,name:"Electronic"},
        TransCategory : {id:1,name:"Food"},
        TransAmount : "8.00",
        TransBalance : "298.00",
        TransNote : "Loren Ipsum",
    },
    {
        TransId:"12",
        AccId : 2,
        TransLib : "Lib transaction id:12 compte id:2",
        TransDate : "27/02/2024",
        TransType : {id:1,name:"Electronic"},
        TransCategory : {id:1,name:"Food"},
        TransAmount : "8.00",
        TransBalance : "298.00",
        TransNote : "Loren Ipsum",
    }
]

export default transactions